name: Windows

on:
  push:
   branches:
      - "windows-ci"

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        BuildType: [Debug, Release]

    defaults:
      run:
        shell: cmd 

    env:
      QT_VERSION: 5.15.2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-tags: true

      - uses: msys2/setup-msys2@v2
        with:
            msystem: mingw32
            release: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          aqtversion: ==3.1.*
          host: windows
          target: desktop
          arch: win32_mingw81
          dir: ${{ runner.temp }}
          modules: qtcharts
          setup-python: true

      - name: Download JOM
        uses: suisei-cn/actions-download-file@v1.6.0
        with:
          url:    http://download.qt.io/official_releases/jom/jom.zip
          target: ${{ runner.temp }}\

      - name: Unzip JOM
        working-directory: ${{ runner.temp }}
        run:  |
              7z x jom.zip -ojom

      - name: Debug
        run:  |
              dir

      - name: Build
        run:  |
              qmake -r QOpenHD.pro
              jom